using Bank.Communication.Application.Contract.Handler;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Text;

namespace Bank.Server.Communication.Controllers
{
	/// <summary>
	/// Handles all Ebics specific communication (via POST) and can return the application information (via GET).
	/// </summary>
	public class EBICSController : Controller
	{
		public EBICSController()
		{
		}

		/// <summary>
		/// Creates the application version info with name and version.
		/// </summary>
		/// <returns>The application info.</returns>
		[HttpGet]
		public string Payment()
		{
			const string version = "Version: {0}";

			StringBuilder builder = new StringBuilder();

			builder.AppendLine(Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationName);

			builder.AppendFormat(version, Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationVersion);

			return builder.ToString();
		}

		/// <summary>
		/// Read a POST request to hande the Ebics data within the request.
		/// </summary>
		/// <param name="handler">The handler generated by dependency injection to process the request data</param>
		[HttpPost]
		public void Ebics([FromServices] IEbicsHandler handler)
		{
			MemoryStream stream = new MemoryStream();
			HttpContext.Request.Body.CopyTo(stream);
			stream.Position = 0;

			HttpContext.Response.Body = handler.ReadData(stream);
		}
	}
}
